### ISSUE TITLE
Thanks a lot for code! Question about data 

### ISSUE THREAD

**Issue by baibizhe** [yyliu01/TraCoCo#3]
Hello .Thanks for this great work!
I am trying to run this project but where which directory should I put the  unlabelled at ?

**Comment by yyliu01** [comment]
I recommend to follows the deployment here (https://github.com/yyliu01/TraCoCo/blob/main/docs/installation.md) before starting. Two datasets should be at the same level as the "Code" folder. Also, please ensure the project is implemented based on the provided conda envs (also in https://github.com/yyliu01/TraCoCo/blob/main/docs/installation.md); otherwise, we cannot guarantee your final result.

**Comment by yyliu01** [comment]
I'm closing the issue. Please feel free to reopen it if your problem is not solved.
